title: 'miguel world'
description: "miguel personal dev blog"
baseurl: ""
url: "https://minkymiguellee.github.io"

header_pages:
  - index.md
  - miguel.md

style: hacker

footer: 'old tistory <a href="https://ml0000.tistory.com">blog</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
