title: 'World Of Miguel'
description: "miguel personal dev blog"
baseurl: ""
url: "https://minkymiguellee.github.io"

header_pages:
  - index.md
  - miguel.md

style: hacker

footer: 'contact <ml0000@naver.com>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
